version: '3.7'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local